#!/bin/sh
set -e

sed -e "s/\${APP_DOMAIN}/$APP_DOMAIN/" -e "s/\${APP_DOMAINS}/$APP_DOMAINS/" deploy/nginx.conf.template > /etc/nginx/conf.d/default.conf

cat deploy/supervisord.docker.conf >> /etc/supervisord.conf

exec /usr/bin/supervisord -n -c /etc/supervisord.conf
