#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


# pai
python /app/manage.py migrate --noinput

# load fixtures
find ./fixtures/*.json -exec python manage.py loaddata {} \;


python /app/manage.py collectstatic --noinput

# pai
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
