#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


# pai
# python manage.py migrate --noinput

# load fixtures
# find ./fixtures -name '*.json' -exec python manage.py loaddata {} \;

python manage.py collectstatic --noinput

# pai
exec python server.py
