from .common import *

# meta
META_DESCRIPTION = env('META_DESCRIPTION', default=APP_DOMAIN)
META_SITE_PROTOCOL = 'https' if DEFAULT_HTTP_PROTOCOL else 'http'
META_USE_SITES = True
# META_SITE_DOMAIN = APP_DOMAIN
META_SITE_NAME = APP_DOMAIN
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True
META_USE_GOOGLEPLUS_PROPERTIES = True
